### ISSUE TITLE
There is no value prop to set value. 

### ISSUE THREAD

**Issue by sandeepg1220** [tuantvk/react-native-datefield#4]
Facing validation issue with no value prop.
For example enter single digit in Year field and click on outside, the field is cleared. how to check whether date fields are empty or not. How to get the value of fileds. If we enter correct date will get the value from onSubmit function. How can I reset date value if we enter wrong value or entering single digit in Year field, in this case there is no callbacks. handleErrors is not calling.

**Comment by tuantvk** [comment]
@sandeepg1220 thanks for issues, please show me code you are using because i wanna know more details about your case.

**Comment by sandeepg1220** [comment]
This is my code.

<DateField
            editable={true}
            labelDate="DD"
            labelMonth="MM"
            labelYear="YYYY"
            value={date}
            styleInput={styles.inputBorder}
            maximumDate={new Date()}
            //minimumDate={new Date(1900, 1, 1)}
            handleErrors={() => {
              console.log('ERROR')
              setDate(null);
            }}
            onSubmit={(value) => {
              console.log('Date:',moment(value).format("DD/MM/YYYY"))
              const currentDate = value || date;
              setDate(currentDate);
            }
            }
          />

One case is if I enter single digit in Year field the date is taking as 1900.
Another scenario is first enter correct date like 01/01/2021. Now clear all the fields. If we look for date value it is still showing previous value instead of null or something as this is due to no event call back if we clear all values in fields

**Comment by tuantvk** [comment]
@sandeepg1220 i have released new version [v0.3.3](https://github.com/tuantvk/react-native-datefield/releases/tag/0.3.3) to update for your issues.
Example in [App.tsx](https://github.com/tuantvk/react-native-datefield/blob/master/example/src/App.tsx)
```js
      <YearMonthDateField
        value={date}
        styleInput={styles.inputBorder}
        onSubmit={(value) => setDate(value)}
      />
      <Button title="Show value" onPress={() => console.log(date)} />
      <Button title="Reset value" onPress={() => setDate(null)} />
```
Year field return 1900 when you enter 1 digit because it is minimum year you can input.
Example:
```
1 -> 1901
92 -> 1992
10 -> 2010
21 -> 2021
```

**Comment by sandeepg1220** [comment]
Thanks a lot @tuantvk . I will check

**Comment by sandeepg1220** [comment]
Hi @tuantvk ,

Is there any style prop for different boxes like date, month, year. In my scenario I want to put year box will be more longer width

**Comment by tuantvk** [comment]
> Hi @tuantvk ,
> 
> Is there any style prop for different boxes like date, month, year. In my scenario I want to put year box will be more longer width

@sandeepg1220 in version `0.3.4`, you can use `styleInputYear ` props

**Comment by sandeepg1220** [comment]
Thanks

**Comment by sandeepg1220** [comment]
Hi @tuantvk ,

Is there any prop to autofocus? I want to focus on input field by default when screen renders

**Comment by tuantvk** [comment]
i add props `autoFocus` in `v0.3.5`, you can check it 036f8e3b176dd402a623a48693ad6ed0f64e47bb

**Comment by sandeepg1220** [comment]
Thanks
