### ISSUE TITLE
Could not find a declaration file for module 'react-native-datefield'

### ISSUE THREAD

**Issue by yehyaumar** [tuantvk/react-native-datefield#5]
When I'm importing this component in typescript, I get this warning. And I don't get autocomplete either. Any suggestions on how to fix it?

**Comment by tuantvk** [comment]
@yehyaumar you can try it:
- create file `index.d.ts` in root project
- add code to file: `declare module 'react-native-datefield';`

Example:
```ts
// index.d.ts
declare module 'react-native-datefield';
```

**Comment by tuantvk** [comment]
updated `v0.3.5` 2ce3361fa393d82c537bfd33e4f66cb7cfa44042

**Comment by yehyaumar** [comment]
Thank you!! 😊
